import LeftSidebar from "@/containers/left-sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex">
          <LeftSidebar />
          <div className="flex grow-[5] mobile:flex-wrap-reverse w-dvw mobile:h-dvh">
            {children}
          </div>
        </main>
        
        </body>
    </html>
  );
}
